In [1]:

import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding



In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [5]:
one_hot('amazing restaurant', 500)

[68, 230]

In [6]:
vocab_size = 30
encoded_reviews =[one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[9, 2],
 [11, 25],
 [1, 27],
 [13, 15, 15],
 [3, 22, 10],
 [26, 2],
 [3, 22, 13],
 [12, 29],
 [12, 5],
 [1, 7]]

In [10]:
max_length = 3
padded_reviews =pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[ 9,  2,  0],
       [11, 25,  0],
       [ 1, 27,  0],
       [13, 15, 15],
       [ 3, 22, 10],
       [26,  2,  0],
       [ 3, 22, 13],
       [12, 29,  0],
       [12,  5,  0],
       [ 1,  7,  0]], dtype=int32)

In [12]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length , name='embedding'))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [11]:
X = padded_reviews
y = sentiment

In [16]:
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten_1 (Flatten)         (None, 12)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 13        
                                                                 
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.fit(X,y,epochs=50, verbose=0)

2023-01-13 10:25:29.742838: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-01-13 10:25:30.112792: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


In [19]:
loss, accuracy =model.evaluate(X,y)
accuracy

1/1 [==============================] - 0s 32ms/step - loss: 0.6561 - accuracy: 0.9000


0.9000000357627869

In [21]:
weights =model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [22]:
weights[11]

array([ 0.06973091, -0.00516066,  0.08499271,  0.00517308], dtype=float32)

In [24]:
weights[3]

array([ 0.04409204, -0.01966422, -0.04658233,  0.00156196], dtype=float32)